### ISSUE TITLE
Injectable Services have their Constructor wrapped, arguments are not delegated

### ISSUE THREAD

**Issue by Phoscur** [joist-framework/joist#1071]
**Describe the bug**
Maybe this should be a feature request, I have probably overlooked a hint in the docs...

**To Reproduce, run:**
```ts
import { injectable } from '@joist/di';

@injectable
class Service {
  constructor(str = 'a') {
    console.log(str);
  }
}
new Service('b');

```

**Expected behavior**
Should print 'b' - forwarding the argument to the orignal constructor
Prints 'a' instead (both v3 & v4.next11)

**Additional context**
I found hints for constructor usage near [the docs for provider factory usage](https://github.com/joist-framework/joist/tree/main/packages/di#factories). 
It would be helpful to be able to also use different constructor arguments for decorated services!

**Comment by deebloo** [comment]
Ummmmm let me check on that. It definitely should forward those on. Should be a pretty small fix if you want to take a look at the injectable decorator.

**Comment by Phoscur** [comment]
Yes just found that, shall I submit a fix with a test?

**Comment by Phoscur** [comment]
Nice, when can I expect new versions? @deebloo 

Sidenote concerning unit tests:
Why the switch from `expect` to `assert`, while chai actually supports both?

**Comment by deebloo** [comment]
Sometimes today. Right now it's time for football :). And no real reason. I prefer assert and it is also the format that the native node assert module uses.

**Comment by deebloo** [comment]
@Phoscur new releases cut for both 4.0 and 3.0

**Comment by Phoscur** [comment]
Nice, I'm on 3.9.2 now and it's fixed! Should I consider upgrading to v4 asap?

**Comment by deebloo** [comment]
Up to you. The di package is really stable. No more changes unless bugs are found.
