### ISSUE TITLE
Is my counter idiomatic?

### ISSUE THREAD

**Issue by georges-gomes** [joist-framework/joist#245]
Hi!

@Nevraeka contacted us to had `joist` to our platform (WebComponents.dev) and also to the next update of [All the ways to make a web component](https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/).

I built this https://webcomponents.dev/edit/1vBcIqaZeu8M14HFOlYO
Is that correct? Is that how you would write it?

Cheers!

**Comment by deebloo** [comment]
Hey @georges-gomes! It looks good.
The only thing I see is that the generic type for State is wrong.
I was playing around with webcomponents.dev earlier today actually made a counter as well.

https://webcomponents.dev/edit/ZwmxGJSHldWQH5T7j8fH

I would either create an interface you can reuse in @component and State or just use a number for the state

**Comment by georges-gomes** [comment]
Oh yes makes sense, I was tired 😄
Cool I'm preparing the starter kit 👍
Thanks!

**Comment by deebloo** [comment]
hey @georges-gomes it looks great! Thank you again! I added a link in the main README :)

**Comment by georges-gomes** [comment]
You are a gentleman ❤️
