### ISSUE TITLE
Custom Element definition order matters

### ISSUE THREAD

**Issue by Phoscur** [joist-framework/joist#957]
**Describe the bug**
It's not directly obvious that custom element parents need to be defined beforehand/in decending order

**To Reproduce**
Using the example from the readme, vite - reverse the definition order:
```js
customElements.define('my-element', MyElement);
customElements.define('color-ctx', ColorCtx);
```

**Expected behavior**
ColorCtx is recognised as parent

**Actual behaviour**
ColorCtx provider overrides are ignored, because it's not recognised as a parent

**Desktop (please complete the following information):**
 - OS: Windows
 
**Additional context**
Took me a few hours debugging in Chromium to find my mistake - can also reproduce in Firefox.

A remark in the readme may be enough to avoid this issue.

**Comment by deebloo** [comment]
Hey that's a good point! Agreed it should be added as a note in the di README. Ill look at add something soon. Happy to review a PR if you have a thought. 

Sorry it tripped you up for so long!

**Comment by deebloo** [comment]
I'm not sure there is. Way to solve it in code, but I do wonder if there is a way make it easier to debug.

**Comment by Phoscur** [comment]
Yes, maybe that's what we actually want, a flag that allows us to explicitly request a parent override, which fails with a nice message/trace making it obvious when parent elements are not providing what they should.

Else it would be great to have a debug util or mode drawing dependency trees!

Provided a PR for a note in the readme, so that closes the issue for now?

**Comment by deebloo** [comment]
Approved and merged! Yeah let's close this issue and I'll open a new one to discuss other on code solutions for debugging. Thanks!
