### ISSUE TITLE
Create a non constructable ProviderToken

### ISSUE THREAD

**Issue by deebloo** [joist-framework/joist#969]
At the moment we assume that all tokens are constructable. This works for 99% of use cases. There are often times where you might want to inject someone other than an object or want to require a specific definition.

An 'InjectionToken<T>' will define a specific symbol to be used in the injection and define the type that the symbol should resolve to. 

```ts
const token = new InjectionToken();
const providers = [{ provide: token, factory: () => {}]
```

The injector would return an error if it is unable to find a provider for the particular token.

**Comment by Phoscur** [comment]
Could even put simple values in there?

```ts
const name = 'Grain';
const token = new InjectionToken(name); // would be nice to optionally give it a name
const providers = [{ provide: token, factory: () => 'Salt']
 ```

**Comment by deebloo** [comment]
Yes this would allow that. Till now I have just used a class with a "value" prop but this would allow any type.

**Comment by deebloo** [comment]
One other note. Adding a default value would be optional. So this would be another way to require manually defending a provider.

**Comment by Phoscur** [comment]
Found a minor issue with the new example in the readme (typescript is complaining), I hope this is related enough:
> Type 'typeof Logger' is not assignable to type 'ProviderToken<any>'.
  Cannot assign an abstract constructor type to a non-abstract constructor type.ts(2322)
provider.d.ts(7, 5): The expected type comes from property 'provide' which is declared here on type 'Provider<any>'
```ts
abstract class Logger {
  abstract log(...args: any[]): void;
}

const app = new Injector([
  {
    provide: Logger as ProviderToken<Logger>, // manual typecast
    factory() {
      return console;
    }
  }
]);

**Comment by deebloo** [comment]
I'll double check the example locally. There should be no need to type cast anything. I think I just have the Logger class those wrong.

**Comment by deebloo** [comment]
@Phoscur ah the problem with the docs is the abstract token. I thought I had added the ability to support abstract classes but turns out that is missing from the provider definition.
