### ISSUE TITLE
Injector with parent Injector ignores its own providers for dependencies

### ISSUE THREAD

**Issue by Phoscur** [joist-framework/joist#993]
**Describe the bug**
My parentInjector only provides Logger, so I thought I could use a childInjector to override a Service, however, in this case it only gives me the overriden Service, when I ask the childInjector directly. If I ask for another Service depending on the overriden one, it will receive the service the (last/topmost?) parentInjector provides unexpectedly. I thought adding layers of childInjectors had exactly this purpose...

**To Reproduce**
```ts
import { inject, injectable, Injector } from '@joist/di';
import { assert } from 'console';

@injectable
class MyService {
  constructor() {
    console.log('MyService created');
  }

  sum() {
    return 42;
  }
}

@injectable
class MyServiceStub extends MyService {
  constructor() {
    super();
    console.log('MyStub created actually');
  }

  sum() {
    return 1;
  }
}

@injectable
class MyOtherService {
  #service = inject(MyService);
  constructor() {
    console.log('MyOtherService created');
  }

  async sum() {
    return this.#service().sum();
  }
}

const injector = new Injector([]); // parent

const myService = injector.get(MyOtherService);
assert((await myService.sum()) === 42, 'unstubbed');

const injectorStub = new Injector([{ provide: MyService, use: MyServiceStub }], injector); // child

const myStub = injectorStub.get(MyService);
const myStud = injectorStub.get(MyOtherService);
assert((await myStub.sum()) === 1, 'stubbed'); // okay
assert((await myStud.sum()) === 1, 'studded'); // fail
```

**Expected behavior**
All Services provided by a ChildInjector should use providers configured in the ChildInjector.

**Environment:**
- OS: Windows
- tsx v4.16.2
- node v21.7.1

**Additional context**
I'm also missing documentation about parent/child injector usage

**Comment by Phoscur** [comment]
I think I'll workaround this for now by creating Injectors from scratch instead of providing parentInjector, until I know how to chain Injectors properly.

**Comment by deebloo** [comment]
So this is currently behaving as expected. But I can see how it might seem odd. It only navigated UP from the injector. Once a provider it found it is costructed with that injector. Let me find a couple of examples that demonstrate the current behavior.

**Comment by deebloo** [comment]
To get around this at the moment you could swap the order and use your current parent as the child. You can use the setParent() method on the injector.

**Comment by deebloo** [comment]
What I am wondering is if each injector should pass its own providers to its parent when set. This would make sure that the parent knew about any providers defined by ita children. These would need to be tracked and removed if the child is removed though... Still need to chew on it a bit

**Comment by Phoscur** [comment]
Would you please explain how parent/child Injectors are intended to be used? 
I thought it was to derive an injector, that would use parent and child providers, prefering the ones in the child - so for example to stub out a service for a test - I have a mainInjector (how does defineEnvironment work on server-side?), and then I create new injectors in test cases, injecting stubs where needed, inheriting or overwriting parent providers.

I can also achieve this by using a common injectorFactory function, which will accept additional providers, so this is not really an issue besides lacking documentation ;)

**Comment by Phoscur** [comment]
Note: this also happens if there was no MyService instance requested before the injectors were defined. So in this case MyOtherService will skip over the existing Stub instance to create a new MyService instance.

**Comment by deebloo** [comment]
Lol you are certainly finding all of the holes in my docs :). So in the current implementation, the injector will only find provided dependencies from the injector it current sits in up. So if you made your stub injector a PARENT of the main injector it would work.

**Comment by Phoscur** [comment]
> Lol you are certainly finding all of the holes in my docs :). So in the current implementation, the injector will only find provided dependencies from the injector it current sits in up. So if you made your stub injector a PARENT of the main injector it would work.

Are you sure, because I tried wrapping into another child and it did not work - it will go to the topmost parent to get the service.

**Comment by deebloo** [comment]
It will go to the topmost parent if a provider is not manually defined yes. It navigates up until it finds a provider if no provider is found it uses the topmost parent. This is so that scoping works from the top down.

**Comment by deebloo** [comment]
https://github.com/joist-framework/joist/blob/main/packages/di/src/lib/injector.ts#L9

**Comment by deebloo** [comment]
Also I wanted to say that I appreciate all of your feedback!

**Comment by Phoscur** [comment]
So what I was expecting is between step 2. and 3.
- check the (child/creating) injector for existing instances of services

**Comment by deebloo** [comment]
It checks itself for cached instances first. An injector has no knowledge of it's children.

**Comment by Phoscur** [comment]
"Itself" meaning static providers on the injected class (Step 2)? 

> An injector has no knowledge of it's children.

No but all its parents! I think I now understand why it works like that, a service instance does not have access/reference to the creating child injector overwriting dependencies. I could add the services that depend on the stub(s) though. So they have the same "provider level".

If I would declare all my explicity providers on the same level it should work.

In this line we get the rootInjector assigned as parent
https://github.com/joist-framework/joist/blob/main/packages/di/src/lib/injector.ts#L66

Can we sneak the childInjector reference in here, so it can be part of the injector chain of dependents?

```ts
    // given longest injector chain
    if (childInjector) 
       return childInjector.get(token, /* stop childInjector recursion */);
    }
    // check for a parent and attempt to get there
    if (this.parent) {
      return this.parent.get(token, this); // sry its so warm and I'm exhausted, is this spaghetti recursion? 
    } else {
      // check if it's really "the root injector"?
    }
```

**Comment by deebloo** [comment]
So it we did that it would break scoping. Imagine if a single parent has multiple children.

**Comment by Phoscur** [comment]
> So it we did that it would break scoping. Imagine if a single parent has multiple children.

In that case I would expect all child services to have their own instances, unless explicitly shared by the root injector provider definition.

So I think this is the core of the issue, would you please document explicit provider definiton for test stubbing?
(And ofc we can continue the discussion about ex- and implicitness, I think can both agree that it would be more intuitive if we inverse that.)

**Comment by deebloo** [comment]
So yes I can show a stub example. However we cannot convert that relationship or the whole web side of things would not work.

**Comment by deebloo** [comment]
new docs added. Still more to think through but this moves the details from comments into the README

https://github.com/joist-framework/joist/tree/main/packages/di#parentchild-relationship

**Comment by Phoscur** [comment]
Okay nice, even with graph! (Reminds me, I wanted to suggest automating plotting dependencies for https://github.com/joist-framework/joist/issues/960) :D

I'm still missing my pitfall to be documented and I think we should use more concrete examples, especially to explain multi-Injector use cases (and ofc every service has its own Injector!).

For a realistic example, let's group services into three kinds: Custom Elements (Frontend), Engine (Shared), Controllers (Backend)
> Elements -> Shared -> defineEnvironment (root)

Actually, there are no additional provider levels with Custom Elements, so custom providers need to be merged into the environment instead:
> Elements -> defineEnvironment (root, Shared providers)


On server-side we have control over the whole injector chain, the Shared package could configure an injector as intermediate provider level:
> Controllers -> Shared -> rootInjector

This could work, but where does one inject specific overrides? The answer is usually needs to be in the root, if default resolution of the Service is used. However, if Shared provides all its Services with explicit resolution, then decorating a single provider factory will not properly overwrite all the Service dependencies (neither via decorating/stubbing Injector inheritance in A, B or R)
> Controller -> StubInjector A -> Shared -> StubInjector B -> rootInjector R

Instead StubInjector A has to copy all relevant explicit provider factories so all relevant Shared services consider that StubInjector their parent and root (a parent Injector only becomes a root it explicitly provides all of its instanciated Services.

```ts
// [code from the top of the issue...]
const injectorStub = new Injector(
  [
    { provide: MyService, use: MyServiceStub },
    { provide: MyOtherService, use: MyOtherService }, // as MyOtherService uses the overriden MyServiceStub, it also needs to be "rooted to this provider level"
  ],
  injector
);

const myS = injectorStub.get(MyOtherService);
console.log((await myS.sum()) === 1, 'it works now');
```
---
So from this we could also try to derive conventions/recommendations:
- Don't use multiple provider levels, it's recommended to only have one parent level of providers defineEnvironment for CustomElements and one "root"-Injector on the Backend, which handles creating all the services, where they may also be overriden, explicitly or not
- If you still want to create your own Injector chain, beware default resolution may be unintuitive and all related provider definitions and overrides need to happen in the same Injector (on the same provider level) explicitly, else Services may resolve with only partially overidden dependencies difficult to debug.

**Comment by deebloo** [comment]
@Phoscur thanks! I will close this now but agree there is room for more improvements. Thanks again for all the feedback!
