### ISSUE TITLE
Function based API for StaticToken and Injector

### ISSUE THREAD

**Issue by deebloo** [joist-framework/joist#999]
Injectors and StaticTokens are created by constructing the provided class. Providing a factory to construct those instances could provide more flexibility since logic can be added during construction. Some folks also just prefer functions. 

This coupled with factories means you could avoid classes all together if you wanted. I personally like use classes and use them often but I know on some teams its common to avoid them.

```ts
import { injector, token } from "@joist/di";

const FETCH_TOKEN = token('fetch', (_: Injector) => {
  return (input: RequestInfo | URL, init?: RequestInit) => fetch(input, init);
});

const app = injector();

const appFetch = app.get(FETCH_TOKEN);

appFetch('/hello-world').then(console.log)
```

**Comment by Phoscur** [comment]
Hiho, just found a use case for the new StaticToken, as a function as mentioned here!
```ts
export const VideoRendererToken = new StaticToken<typeof stitchImages>(
  'VideoRenderer',
  () => stitchImages
);
``` 
Now, when I want to inject it, am missing something...

```ts
@injectable
export class Timelapse {
  #renderer = inject(VideoRendererToken); // !TS2345 constructor is missing
[...]
```

**Comment by deebloo** [comment]
@Phoscur can you open this as a new issue and post a reproduction? I want to add the scenario to the unit test to find out what's happening

**Comment by deebloo** [comment]
@Phoscur I know the problem. I missed updating on typescript definition. will fix and push tonight

**Comment by deebloo** [comment]
eh I am closing this for now. It would be easy enough for a user that prefers functions to  wrap the classes themselves
